### ISSUE TITLE
کار نکردن اسکریپت با ای پی های سفارشی

### ISSUE THREAD

**Issue by retina20** [Nalbekink/V2ray-Cloudflare#2]
درود.
با وارد کردن ای پی های سفارشی از سمت کاربر چه در بخش ریجکس چه در بخش جدید که تنها میتوان از یک رنج پینگ گرفت , اسکریپت ران نمیشه و صرفا آنی پیغام پایان میدهد. این ایراد فقط برای رنج آی پی هایی که دستی و در لیست خود اسکریپت تعریف نشده وجود دارد.
من بررسی کردم در صورتی که رنج در فایل index.html وجود نداشته باشد و به صورتی دستی رنج جدیدی در مرورگر وارد شود ؛ اسکریپت ران نمیشود.
با تشکر از تلاش های قابل شما برای اینترنت آزاد.

**Comment by Nalbekink** [comment]
فرمت ورودی ip range ها به صورت regex نیست بلکه باید هر ip range را طبق فرمت CIDR وارد کنید.

**Comment by retina20** [comment]
close
